default: &DEFAULT
  GOOGLE_CLOUD_PROJECT : "sandbox-159310"
  GOOGLE_CLOUD_KEYFILE : "config/stackdriver_keyfiles/staging.json"

development:
  <<: *DEFAULT

staging:
  <<: *DEFAULT

production:
  <<: *DEFAULT